db:
  username: username
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 12
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    com.kxnvg.spring.database.pool: INFO
    org.springframework.jdbc.core: TRACE


spring.profiles.active: qa

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl: validate
        jdbc:
          batch_size: 50
          fetch_size: 10
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 306416224059-og7stv5oqnr1va1kbhuai1rj6etan4do.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile


springdoc:
  api-docs:
    path : /api-docs
  swagger-ui:
    oauth:
      client-id: 306416224059-og7stv5oqnr1va1kbhuai1rj6etan4do.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
